#!/usr/bin/env bash
# Interactively prompt for Alpaca paper API credentials and write .env.
# Run once: bash automation/setup-credentials.sh
set -e

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

echo "==================================================================="
echo "  Alpaca paper trading credentials setup"
echo "==================================================================="
echo
echo "If you don't have credentials yet:"
echo "  1. Sign up (free) at https://alpaca.markets"
echo "  2. Open https://app.alpaca.markets/paper/dashboard/overview"
echo "  3. On the right side, click 'View' or 'Generate New Key' under"
echo "     'Your API Keys'"
echo "  4. Copy the Key ID and Secret Key"
echo
echo "Paste them below. Input is hidden for the secret."
echo

read -r -p "Alpaca paper API Key (Key ID): " KEY
echo
read -r -s -p "Alpaca paper API Secret: " SECRET
echo
echo

if [ -z "$KEY" ] || [ -z "$SECRET" ]; then
    echo "ERROR: Both Key and Secret are required." >&2
    exit 1
fi

cat > .env <<EOF
# Generated by automation/setup-credentials.sh on $(date -u +%FT%TZ)
ALPACA_API_KEY=$KEY
ALPACA_API_SECRET=$SECRET
ALPACA_BASE_URL=https://paper-api.alpaca.markets

# Real-money trading is intentionally not implemented in this repo.
TRADER_LIVE_REAL_MONEY=0
EOF
chmod 600 .env

echo "Wrote .env (permissions 600)."
echo
echo "Next: run the first paper trade."
echo "  bash automation/first-run.sh"
